name: auto_route_demo
description: A new Flutter project for demonstrate auto route package

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^3.0.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
